# Site settings
title: Tangential Labs
description: > # this means to ignore newlines until "baseurl:"
  A software dev with a penchant for game and server-side code.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://j3hyde.github.io" # the base hostname & protocol for your site
twitter_username: j3hyde
github_username:  j3hyde

# Build settings
markdown: kramdown

owner:
  name: Jeffrey Kyllo
  avatar: avatar.jpeg
  twitter: j3hyde
  github: j3hyde
timezone: United_Kingdom/London
markdown: kramdown

paginate: 3

